# Generated by Django 4.2.7 on 2023-12-13 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsitePages', '0004_rename_buyer_datastorage_buyer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastorage',
            old_name='buyer',
            new_name='buyer_name',
        ),
        migrations.DeleteModel(
            name='BasketItem',
        ),
    ]
